name: Bing Daily Wallpaper

# 定时触发 + 手动触发
on:
  workflow_dispatch:
  schedule:
    # 每天日本时间 0:10 执行 (UTC+9 = UTC 15:10)
    - cron: '10 15 * * *'

jobs:
  download-and-notify:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 下载壁纸
      - name: Run wallpaper script
        id: download
        run: |
          chmod +x ./scripts/get-wallpaper.sh
          ./scripts/get-wallpaper.sh
        continue-on-error: true  # 即使失败也继续执行

      # 3️⃣ Commit & Push 新壁纸
      - name: Commit & Push new wallpaper
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wallpapers/
          git add script/log/   # 添加日志文件夹
          git commit -m "Add new Bing wallpaper and logs on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        continue-on-error: true

      # 4️⃣ 发送邮件通知
      - name: Run PowerShell Notification
        shell: pwsh
        if: always()  # 无论前一步成功或失败都执行
        env:
          RESEND_API_TOKEN: ${{ secrets.RESEND_API_TOKEN }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          ACTION_RESULT: ${{ steps.download.outcome }}  # 获取下载步骤状态
        run: pwsh ./scripts/email.ps1
